<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
<!-- Generated by NotebookLM Corrected Mindmap Extractor v6.0 with X-Level Parent-Child Logic -->
  <node ID="node_0" TEXT="هیپوگلایسمی در اطفال (پاتوفیزیولوژی و علل)">
    <node ID="node_1" TEXT="پاتوفیزیولوژی گلوکز">
      <node ID="node_8" TEXT="سوخت اصلی مغز">
        <node ID="node_27" TEXT="تولید ATP (هر مول گلوکز 38 مول)">
        </node>
        <node ID="node_28" TEXT="سوخت جایگزین: کتون">
        </node>
      </node>
      <node ID="node_9" TEXT="منابع ذخیره گلوکز">
      </node>
      <node ID="node_10" TEXT="همئوستاز گلوکز">
        <node ID="node_29" TEXT="سیستم هورمونی">
        </node>
        <node ID="node_30" TEXT="تعامل انسولین و هورمون‌های مقابله‌کننده">
        </node>
      </node>
    </node>
    <node ID="node_2" TEXT="همئوستاز گلوکز (وضعیت‌ها)">
      <node ID="node_11" TEXT="Post-fed (پس از تغذیه)">
        <node ID="node_31" TEXT="ترشح انسولین">
        </node>
        <node ID="node_32" TEXT="Uptake گلوکز توسط سلول‌های محیطی">
        </node>
        <node ID="node_33" TEXT="سنتز گلیکوژن در کبد">
        </node>
      </node>
      <node ID="node_12" TEXT="Fasting (ناشتایی)">
        <node ID="node_34" TEXT="کاهش ترشح انسولین">
        </node>
        <node ID="node_35" TEXT="افزایش هورمون‌های Counter Regulatory">
          <node ID="node_81" TEXT="گلوکاگون (اثر اولیه)">
          </node>
          <node ID="node_82" TEXT="اپی نفرین">
          </node>
          <node ID="node_83" TEXT="GH (هورمون رشد)">
          </node>
        </node>
        <node ID="node_36" TEXT="منابع تولید گلوکز">
          <node ID="node_84" TEXT="گلیکوژنولیز (سریع‌ترین منبع)">
            <node ID="node_104" TEXT="گلیکوژن کبدی">
            </node>
            <node ID="node_105" TEXT="فعال شدن 6 تا 12 ساعت اول">
            </node>
          </node>
          <node ID="node_85" TEXT="گلوکونئوژنز (بعد از گلیکوژن)">
            <node ID="node_106" TEXT="فعال شدن 6 تا 12 ساعت بعد">
            </node>
            <node ID="node_107" TEXT="پیش‌سازها: آلانین (عضله), گلیسرول, لاکتات">
            </node>
          </node>
          <node ID="node_86" TEXT="لیپولیز و کتوژنز">
            <node ID="node_108" TEXT="فعال شدن در طولانی شدن fasting">
            </node>
            <node ID="node_109" TEXT="تولید کتون (سوخت جایگزین مغز)">
            </node>
          </node>
        </node>
      </node>
    </node>
    <node ID="node_3" TEXT="هایپوگلایسمی در نوزادان">
      <node ID="node_13" TEXT="مکانیسم اولیه">
        <node ID="node_37" TEXT="وابستگی به گلوکز مادر در رحم">
        </node>
        <node ID="node_38" TEXT="قطع بند ناف ← اتکا به ذخایر داخلی">
        </node>
      </node>
      <node ID="node_14" TEXT="نوزادان High Risk">
        <node ID="node_39" TEXT="متولد شده از مادران دیابتی (هایپرانسولینیسم)">
        </node>
        <node ID="node_40" TEXT="SGA (Small for Gestational Age)">
        </node>
        <node ID="node_41" TEXT="Premature (زودرس)">
        </node>
        <node ID="node_42" TEXT="استرس در اواخر بارداری (اسفیکسی, پره‌اکلامپسی)">
        </node>
      </node>
      <node ID="node_15" TEXT="علائم در سنین پایین">
        <node ID="node_43" TEXT="فاقد علائم اتونومیک">
        </node>
        <node ID="node_44" TEXT="لرزش اندام‌ها، آپنه، سیانوز، تشنج">
        </node>
      </node>
    </node>
    <node ID="node_4" TEXT="علل و مکانیسم‌های هایپوگلایسمی">
      <node ID="node_16" TEXT="افزایش عملکرد انسولین (Excess Insulin Action)">
        <node ID="node_45" TEXT="نوزاد مادر دیابتی (موقت)">
        </node>
        <node ID="node_46" TEXT="هایپرانسولینیسم (Persistant)">
        </node>
        <node ID="node_47" TEXT="آدنوم سلول‌های پانکراس">
        </node>
        <node ID="node_48" TEXT="سولفونیل اوره (توکسیسیته دارویی)">
        </node>
        <node ID="node_49" TEXT="هایپوگلایسمی مصرفی (Hyperinsulinism)">
        </node>
        <node ID="node_50" TEXT="Factitious Hyperinsulinemia (سندروم مونکهاوزن)">
        </node>
      </node>
      <node ID="node_17" TEXT="کمبود/اختلال هورمون‌های مقابله‌کننده">
        <node ID="node_51" TEXT="نارسایی اولیه آدرنال (کمبود کورتیزول)">
          <node ID="node_87" TEXT="مراجعه با شوک و اختلال الکترولیتی">
          </node>
        </node>
        <node ID="node_52" TEXT="نارسایی آدرنال ثانویه (کاهش ACTH)">
        </node>
        <node ID="node_53" TEXT="کمبود GH (هورمون رشد)">
          <node ID="node_88" TEXT="تشخیص با کوتاه‌قدی">
          </node>
          <node ID="node_89" TEXT="Pan-hypopitutarism (چند نقص هیپوفیزی)">
          </node>
        </node>
      </node>
      <node ID="node_18" TEXT="اختلال در مسیرهای تولید و ذخیره گلوکز">
        <node ID="node_54" TEXT="نقص سوبسترا (لاغری، SGA، Premature)">
          <node ID="node_90" TEXT="گلیکوژن/چربی زیرجلدی کم">
          </node>
          <node ID="node_91" TEXT="بافت عضلانی کم (آلانین ناکافی)">
          </node>
        </node>
        <node ID="node_55" TEXT="بیماری‌های ذخیره‌ای گلیکوژن (GSD)">
          <node ID="node_92" TEXT="اختلال در آنزیم‌های گلیکوژنولیز">
          </node>
          <node ID="node_93" TEXT="GSD نوع I (اختلال گلوکونئوژنز و گلیکوژنولیز)">
          </node>
          <node ID="node_94" TEXT="علائم: کبد بزرگ (هپاتومگالی)">
          </node>
        </node>
        <node ID="node_56" TEXT="اختلال گلوکونئوژنز">
          <node ID="node_95" TEXT="نقص آنزیم‌هایی مثل فروکتوز 1و6 بیس فسفاتاز">
          </node>
          <node ID="node_96" TEXT="تحمل نکردن Fasting طولانی">
          </node>
          <node ID="node_97" TEXT="همراهی با لاکتات بالا و اسیدوز">
          </node>
        </node>
        <node ID="node_57" TEXT="اختلال اکسیداسیون اسید چرب">
          <node ID="node_98" TEXT="موجب Non-Ketotic Hypoglycemia">
          </node>
        </node>
      </node>
    </node>
    <node ID="node_5" TEXT="انواع هایپوگلایسمی بر اساس کتون">
      <node ID="node_19" TEXT="کتوتیک هایپوگلایسمی (Ketotic)">
        <node ID="node_58" TEXT="کتون در خون/ادرار مثبت است">
        </node>
        <node ID="node_59" TEXT="شامل اغلب انواع هایپوگلایسمی (مثل GSD)">
        </node>
        <node ID="node_60" TEXT="Idiopathic Ketotic Hypoglycemia">
          <node ID="node_99" TEXT="شایع در Toddler و Young Children (18 ماهگی تا 5-7 سالگی)">
          </node>
          <node ID="node_100" TEXT="Fasting طولانی (12-18 ساعت) باعث افت قند">
          </node>
          <node ID="node_101" TEXT="علت: کمبود سوبسترای گلوکونئوژنز (آلانین کم)">
          </node>
        </node>
      </node>
      <node ID="node_20" TEXT="نان-کتوتیک هایپوگلایسمی (Non-Ketotic)">
        <node ID="node_61" TEXT="کتون منفی است (آسیب‌پذیری بیشتر مغز)">
          <node ID="node_102" TEXT="هایپرانسولینیسم (انسولین بالا لیپولیز را مهار می‌کند)">
          </node>
          <node ID="node_103" TEXT="اختلال اکسیداسیون اسید چرب (مشکل آنزیمی)">
          </node>
        </node>
      </node>
    </node>
    <node ID="node_6" TEXT="تظاهرات بالینی (علائم)">
      <node ID="node_21" TEXT="علائم اتونوم (تحریک سیستم اتونوم)">
        <node ID="node_62" TEXT="تعریق، لرزش، تپش قلب">
        </node>
        <node ID="node_63" TEXT="احساس گرسنگی (قند زیر 60)">
        </node>
      </node>
      <node ID="node_22" TEXT="نوروگلایکوپنیا (افت قند در مغز)">
        <node ID="node_64" TEXT="سردرد، سرگیجه">
        </node>
        <node ID="node_65" TEXT="اختلال دید (دوبینی)">
        </node>
        <node ID="node_66" TEXT="تغییرات شخصیتی (خشونت، بی‌قراری)">
        </node>
        <node ID="node_67" TEXT="کاهش سطح هوشیاری و تشنج (علائم شایع مراجعه)">
        </node>
      </node>
    </node>
    <node ID="node_7" TEXT="ارزیابی و تشخیص">
      <node ID="node_23" TEXT="زمان‌بندی بروز">
        <node ID="node_68" TEXT="Neonatal Period / Early Infancy: هایپرانسولینیسم، Panhypopitutarism">
        </node>
        <node ID="node_69" TEXT="1-2 سال اول: GSD، کمبود کورتیزول/GH">
        </node>
        <node ID="node_70" TEXT="Young Children / Toddlers: کتوتیک هیپوگلایسمی، مسمومیت دارویی (Poisoning)">
        </node>
      </node>
      <node ID="node_24" TEXT="معاینه فیزیکی و نشانه‌ها">
        <node ID="node_71" TEXT="Anthropometrics (قد، وزن، جثه)">
        </node>
        <node ID="node_72" TEXT="نقایص خط وسط (Midline Defect) ← مشکلات مغزی">
        </node>
        <node ID="node_73" TEXT="Hepatomgaly (مشکلات متابولیک)">
        </node>
        <node ID="node_74" TEXT="ماکروگلوسی و فتق نافی (Beckwith-Wiedemann)">
        </node>
        <node ID="node_75" TEXT="هایپرپیگمانتاسیون (نارسایی اولیه آدرنال)">
        </node>
      </node>
      <node ID="node_25" TEXT="Critical Sample (نمونه خون حیاتی)">
        <node ID="node_76" TEXT="گرفته شده همزمان با افت قند">
        </node>
        <node ID="node_77" TEXT="اندازه‌گیری انسولین، هورمون‌ها و کتون">
        </node>
        <node ID="node_78" TEXT="در Factitious: انسولین بالا, C-peptide پایین (Undetectable)">
        </node>
      </node>
      <node ID="node_26" TEXT="Triggers (عوامل محرک)">
        <node ID="node_79" TEXT="بیماری همزمان/کاهش Intake (تب، عفونت)">
        </node>
        <node ID="node_80" TEXT="Duration of Fasting (Short vs Longer)">
        </node>
      </node>
    </node>
  </node>
</map>