<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
<!-- Generated by NotebookLM Corrected Mindmap Extractor v6.0 with X-Level Parent-Child Logic -->
  <node ID="node_0" TEXT="هایپوگالیسمی (Hypoglycemia)">
    <node ID="node_1" TEXT="پاتوفیزیولوژی گلوکز و مغز">
      <node ID="node_10" TEXT="استفاده مغز از کتون">
        <node ID="node_42" TEXT="در صورت کاهش گلوکز">
        </node>
        <node ID="node_39" TEXT="سوخت اصلی مغز">
        </node>
        <node ID="node_40" TEXT="منبع تولید انرژی (38 مول ATP)">
        </node>
        <node ID="node_41" TEXT="ذخیره به صورت گلیکوژن، چربی و پروتئین">
        </node>
      </node>
    </node>
    <node ID="node_2" TEXT="هایپوگالیسمی در نوزادان">
      <node ID="node_11" TEXT="وابستگی جنین">
        <node ID="node_43" TEXT="منبع گلوکز: گلوکز مادر">
        </node>
        <node ID="node_44" TEXT="نوسانات مادر بر جنین اثر می‌گذارد">
        </node>
      </node>
      <node ID="node_12" TEXT="پس از تولد">
        <node ID="node_45" TEXT="قطع منبع گلوکز (بند ناف)">
        </node>
        <node ID="node_46" TEXT="وابسته به ذخایر گلوکز و چربی">
        </node>
        <node ID="node_47" TEXT="سطح گلوکز 2-3 ساعت بعد به پایین‌ترین حد می‌رسد">
        </node>
        <node ID="node_48" TEXT="فول ترم باید هومئوستاز را 24-48 ساعت بعد انجام دهد (BS=65)">
        </node>
      </node>
      <node ID="node_13" TEXT="نوزادان High Risk (پرخطر)">
        <node ID="node_49" TEXT="SGA (وزن کم نسبت به سن حاملگی)">
        </node>
        <node ID="node_50" TEXT="نوزادان مادران دیابتی (هایپرانسولینیسم به دلیل هایپرپالزی پانکراس)">
        </node>
        <node ID="node_51" TEXT="Premature (نارس)">
        </node>
        <node ID="node_52" TEXT="ذخیره ناکافی گلیکوژن و چربی زیر جلدی (SGA و Premature)">
        </node>
        <node ID="node_53" TEXT="نوزادان تحت استرس (آسفیکسی، اکلامپسی/پره اکلامپسی مادر)">
        </node>
      </node>
    </node>
    <node ID="node_3" TEXT="تعاریف و اندازه‌گیری">
      <node ID="node_14" TEXT="روش اندازه گیری">
        <node ID="node_54" TEXT="پلاسما (اساس اندازه‌گیری قند خون)">
        </node>
        <node ID="node_55" TEXT="گلوکومتر (قند خون whole blood)">
        </node>
      </node>
      <node ID="node_15" TEXT="تفاوت پلاسما و Whole Blood">
        <node ID="node_56" TEXT="گلوکز سرم 10-15 درصد بالاتر است">
        </node>
      </node>
      <node ID="node_16" TEXT="تعریف هایپوگالیسمی">
        <node ID="node_57" TEXT="قند زیر 50 (در تمامی گایدلاین‌ها)">
        </node>
      </node>
      <node ID="node_17" TEXT="تریاد ویپل (Whipple&apos;s Triad)">
        <node ID="node_58" TEXT="قند خون پایین">
        </node>
        <node ID="node_59" TEXT="علائم اتونوم مربوط به هایپوگالیسمی">
        </node>
        <node ID="node_60" TEXT="برطرف شدن علائم با دریافت گلوکز">
        </node>
        <node ID="node_61" TEXT="در شیرخوارگی/اوایل نوزادی دیده نمی‌شود">
        </node>
      </node>
    </node>
    <node ID="node_4" TEXT="هموستاز گلوکز (حفظ تعادل)">
      <node ID="node_18" TEXT="نیاز به مسیرهای آنزیمی سالم">
      </node>
      <node ID="node_19" TEXT="نقش سیستم هورمونی">
        <node ID="node_62" TEXT="هورمون‌های Counter regulatory">
          <node ID="node_107" TEXT="GH">
          </node>
          <node ID="node_108" TEXT="اپی نفرین">
          </node>
        </node>
      </node>
      <node ID="node_20" TEXT="وضعیت تغذیه">
        <node ID="node_63" TEXT="Post Fed (پس از غذا)">
          <node ID="node_109" TEXT="ترشح انسولین">
          </node>
          <node ID="node_110" TEXT="Uptake گلوکز توسط سلول‌های محیطی">
          </node>
          <node ID="node_111" TEXT="تولید گلیکوژن در کبد">
          </node>
        </node>
        <node ID="node_64" TEXT="Fast (ناشتایی)">
          <node ID="node_112" TEXT="کاهش ترشح انسولین">
          </node>
          <node ID="node_113" TEXT="افزایش Counter regulatory hormones (اگر گلوکز زیر 70 برسد)">
          </node>
        </node>
      </node>
      <node ID="node_21" TEXT="منابع بدن برای تولید گلوکز">
        <node ID="node_65" TEXT="گلیکوژن کبدی (منبع اصلی و سریع)">
          <node ID="node_114" TEXT="ذخیره 6 تا 12 ساعت نیاز بچه را تامین می‌کند">
          </node>
          <node ID="node_115" TEXT="کودکان ریزجثه: 3 تا 4 ساعت">
          </node>
        </node>
        <node ID="node_66" TEXT="گلوکونئوژنز (چند ساعت پس از تغذیه فعال می‌شود)">
          <node ID="node_116" TEXT="منبع اصلی: اسید آمینه (آلانین از عضله)">
          </node>
          <node ID="node_117" TEXT="منابع دیگر: لاکتات، گلیسرول">
          </node>
        </node>
        <node ID="node_67" TEXT="اسیدهای چرب (در فاستینگ طولانی)">
        </node>
      </node>
    </node>
    <node ID="node_5" TEXT="زمان بروز نقایص متابولیکی">
      <node ID="node_22" TEXT="اوایل شیرخوارگی (2-3 ساعته)">
        <node ID="node_68" TEXT="تغذیه مکرر؛ نقص مشخص نمی‌شود">
        </node>
      </node>
      <node ID="node_23" TEXT="3 تا 6 ماهگی (فواصل 4-6 ساعته)">
        <node ID="node_69" TEXT="وابستگی به گلیکوژن: نقص مشخص می‌شود">
        </node>
        <node ID="node_70" TEXT="گلوکونئوژنز مشکل داشته باشد: دیرتر مشخص می‌شود (با فاستینگ طولانی)">
        </node>
      </node>
    </node>
    <node ID="node_6" TEXT="اهمیت کتون">
      <node ID="node_24" TEXT="سوخت جایگزین برای تولید ATP">
      </node>
      <node ID="node_25" TEXT="کمک به مغز برای کاهش آسیب">
      </node>
      <node ID="node_26" TEXT="کتون مثبت">
        <node ID="node_71" TEXT="نشان‌دهنده فعال بودن لیپولیز و تولید کتون">
        </node>
      </node>
      <node ID="node_27" TEXT="کتون منفی (هشدار)">
        <node ID="node_72" TEXT="تولید کتون مختل شده">
        </node>
        <node ID="node_73" TEXT="آسیب بیشتری به مغز وارد می‌شود">
        </node>
      </node>
    </node>
    <node ID="node_7" TEXT="علل و پاتوفیزیولوژی هایپوگالیسمی">
      <node ID="node_28" TEXT="Excess Insulin Action (افزایش انسولین)">
        <node ID="node_74" TEXT="نوزاد مادر دیابتی">
        </node>
        <node ID="node_75" TEXT="موتاسیون سلول B پانکراس">
        </node>
        <node ID="node_76" TEXT="انسولینوم/آدنوم (در بچه‌های بزرگتر)">
        </node>
        <node ID="node_77" TEXT="مصرف دارویی (سولفونیل اوره)">
        </node>
        <node ID="node_78" TEXT="Factitious hyperinsulinemia">
          <node ID="node_118" TEXT="انسولین اگزوژن زیاد (سندروم Munchausen)">
          </node>
          <node ID="node_119" TEXT="تشخیص: C-peptide پایین/undetectable">
          </node>
        </node>
      </node>
      <node ID="node_29" TEXT="Counter Regulatory Hormone ناکافی">
        <node ID="node_79" TEXT="نارسایی اولیه آدرنال (کورتیزول پایین)">
        </node>
        <node ID="node_80" TEXT="نارسایی ثانویه آدرنال (مشکل در هیپوفیز)">
        </node>
        <node ID="node_81" TEXT="Pan-hypopituitarism (کمبود GH و کورتیزول)">
        </node>
      </node>
      <node ID="node_30" TEXT="نقایص مسیرهای متابولیک">
        <node ID="node_82" TEXT="اختلال در گلیکوژنولیز (GSD)">
          <node ID="node_120" TEXT="آنزیم شکستن گلیکوژن اختلال دارد">
          </node>
          <node ID="node_121" TEXT="Type I GSD (اختلال در آنزیم انتهایی): کبد بزرگ، هیپوگالیسمی">
          </node>
        </node>
        <node ID="node_83" TEXT="اختلال در گلوکونئوژنز">
          <node ID="node_122" TEXT="فستینگ کوتاه را تحمل می‌کنند">
          </node>
          <node ID="node_123" TEXT="فستینگ طولانی را تحمل نمی‌کنند">
          </node>
          <node ID="node_124" TEXT="علائم: کبد بزرگ، کبد چرب، لاکتات بالا">
          </node>
        </node>
      </node>
      <node ID="node_31" TEXT="سوبسترای ناکافی">
        <node ID="node_84" TEXT="شایع‌ترین: SGA یا Premature (ذخایر کم گلیکوژن و چربی)">
        </node>
        <node ID="node_85" TEXT="Idiopathic Ketotic Hypoglycemia">
          <node ID="node_125" TEXT="در Toddlers و Young children (18 ماهگی تا 8 سالگی)">
          </node>
          <node ID="node_126" TEXT="عدم آلانین کافی (در بچه‌های لاغر)">
          </node>
          <node ID="node_127" TEXT="عدم تحمل فستینگ طولانی (بیش از 12-18 ساعت)">
          </node>
          <node ID="node_128" TEXT="درمان: رژیم پرپروتئین">
          </node>
        </node>
      </node>
    </node>
    <node ID="node_8" TEXT="طبقه‌بندی و تشخیص">
      <node ID="node_32" TEXT="تقسیم‌بندی بر اساس کتون">
        <node ID="node_86" TEXT="Ketotic Hypoglycemia (کتون مثبت)">
          <node ID="node_129" TEXT="افت قند + کتون مثبت (مسیر لیپولیز سالم)">
          </node>
        </node>
        <node ID="node_87" TEXT="Non-Ketotic Hypoglycemia (کتون منفی - خطرناک)">
          <node ID="node_130" TEXT="افت قند + کتون منفی">
          </node>
          <node ID="node_131" TEXT="علل: هایپرانسولینمی، اختلال در اکسیداسیون اسید چرب">
          </node>
        </node>
      </node>
      <node ID="node_33" TEXT="طبقه‌بندی بر اساس سن و Triggers">
        <node ID="node_88" TEXT="Neonatal / Early Infancy">
          <node ID="node_132" TEXT="هایپرانسولینیسم، Panhypopituitarism">
          </node>
        </node>
        <node ID="node_89" TEXT="Toddlers / Young Children">
          <node ID="node_133" TEXT="Ketotic Hypoglycemia، GSD، Poisoning">
          </node>
        </node>
        <node ID="node_90" TEXT="فستینگ کوتاه (Short duration)">
          <node ID="node_134" TEXT="هایپرانسولینمی، GSD (I, III)">
          </node>
        </node>
        <node ID="node_91" TEXT="فستینگ طولانی (Longer duration)">
          <node ID="node_135" TEXT="اختلال گلوکونئوژنز، اختلال اکسیداسیون اسید چرب">
          </node>
        </node>
      </node>
      <node ID="node_34" TEXT="نمونه خون بحرانی (Critical Sample)">
        <node ID="node_92" TEXT="زمان: دقیقاً وقتی قند خون پایین است">
        </node>
        <node ID="node_93" TEXT="هدف: بررسی پاسخ بدن (انسولین، هورمون‌های Counter-regulatory)">
        </node>
      </node>
      <node ID="node_35" TEXT="معاینه فیزیکی (نکات کلیدی)">
        <node ID="node_94" TEXT="Anthropometrics (قد و وزن)">
        </node>
        <node ID="node_95" TEXT="Midline Defect (نقایص خط وسط) - شک به کمبود هیپوفیز">
        </node>
        <node ID="node_96" TEXT="هپاتومگالی (شک به GSD)">
        </node>
        <node ID="node_97" TEXT="Macroglossia، فتق نافی (شک به سندروم Beckwith-Wiedemann)">
        </node>
        <node ID="node_98" TEXT="هایپرپیگمانتاسیون (شک به نارسایی اولیه آدرنال)">
        </node>
      </node>
    </node>
    <node ID="node_9" TEXT="تظاهرات بالینی">
      <node ID="node_36" TEXT="در سنین پایین (نوزادی/شیرخوارگی)">
        <node ID="node_99" TEXT="علائم غیراختصاصی (عدم بروز علائم اتونوم)">
        </node>
        <node ID="node_100" TEXT="لرزش اندام‌ها">
        </node>
        <node ID="node_101" TEXT="تشنج (Seizure)">
        </node>
        <node ID="node_102" TEXT="آپنه، سیانوز، هایپوتون شدن">
        </node>
        <node ID="node_103" TEXT="شیر نخوردن خوب">
        </node>
      </node>
      <node ID="node_37" TEXT="در سنین بالاتر (قند زیر 50)">
        <node ID="node_104" TEXT="علائم تحریک سیستم اتونوم (آزادسازی اپی نفرین)">
          <node ID="node_136" TEXT="Anxiety (مضطرب)">
          </node>
          <node ID="node_137" TEXT="Perspiration (تعریق)">
          </node>
          <node ID="node_138" TEXT="Palpitation (تپش قلب)">
          </node>
          <node ID="node_139" TEXT="Tremulousness (لرزش)">
          </node>
          <node ID="node_140" TEXT="Weakness">
          </node>
          <node ID="node_141" TEXT="Hunger، Nausea">
          </node>
        </node>
        <node ID="node_105" TEXT="علائم Cerebral Glucopenia (افت قند در مغز)">
          <node ID="node_142" TEXT="Headache، Dizziness">
          </node>
          <node ID="node_143" TEXT="Mental confusion (گیجی)">
          </node>
          <node ID="node_144" TEXT="Visual disturbances (تاری دید، دوبینی)">
          </node>
          <node ID="node_145" TEXT="تغییرات شخصیتی (بداخلاقی)">
          </node>
          <node ID="node_146" TEXT="عدم تمرکز، Staring">
          </node>
          <node ID="node_147" TEXT="شایع‌ترین: Seizure و اختلال هوشیاری">
          </node>
        </node>
      </node>
      <node ID="node_38" TEXT="نکته نهایی">
        <node ID="node_106" TEXT="آسیب مغزی با شدت و طولانی بودن هایپوگالیسمی افزایش می‌یابد">
        </node>
      </node>
    </node>
  </node>
</map>
