<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
<!-- Generated by NotebookLM Corrected Mindmap Extractor v6.0 with X-Level Parent-Child Logic -->
  <node ID="node_0" TEXT="عفونت‌های دستگاه تنفسی (اطفال)">
    <node ID="node_1" TEXT="اپروچ اولیه به بیمار تنفسی">
      <node ID="node_10" TEXT="تقسیم‌بندی اولیه">
        <node ID="node_43" TEXT="Upper Respiratory Tract Infection">
        </node>
        <node ID="node_44" TEXT="Lower Respiratory Tract Infection">
        </node>
      </node>
      <node ID="node_11" TEXT="طیف عفونت‌های تنفسی">
        <node ID="node_45" TEXT="فارنژیت ساده">
        </node>
        <node ID="node_46" TEXT="حاد و مزمن">
        </node>
      </node>
      <node ID="node_12" TEXT="مشکلات تنفسی در کودکان">
        <node ID="node_47" TEXT="بسیار شایع">
        </node>
        <node ID="node_48" TEXT="علل اصلی مرگ و میر در جهان سوم (همراه با عفونت گوارشی)">
        </node>
        <node ID="node_49" TEXT="تظاهر اولیه گاهی به صورت سندرم‌ها">
        </node>
        <node ID="node_50" TEXT="علائم بالینی قبل از تصویربرداری غیرطبیعی">
        </node>
        <node ID="node_51" TEXT="عفونت‌های Lower Tract به ندرت از ابتدا علامت‌دار">
        </node>
      </node>
    </node>
    <node ID="node_2" TEXT="اتیولوژی عفونت‌های سیستم تنفسی">
      <node ID="node_13" TEXT="1. Genetic Abnormality">
        <node ID="node_52" TEXT="سیستیس فیبروزیس (CF)">
        </node>
        <node ID="node_53" TEXT="اختلال آناتومیک (مثال لارنگو مالاشی)">
        </node>
        <node ID="node_54" TEXT="Incomplete maturation (مثال برونکوپولمونار دیسپالزی)">
        </node>
      </node>
      <node ID="node_14" TEXT="2. Iatrogenic Disorder">
        <node ID="node_55" TEXT="آسیب ناشی از ونتیلاتور (پنومونی متعاقب)">
        </node>
      </node>
      <node ID="node_15" TEXT="3. Immunologic Disorder (SCID)">
      </node>
      <node ID="node_16" TEXT="4. Infectious Disease (مثال پنومونی)">
      </node>
      <node ID="node_17" TEXT="5. Environmental Exposure (مثال آلودگی)">
      </node>
      <node ID="node_18" TEXT="6. Extra Pulmonary (مثال CHD)">
      </node>
    </node>
    <node ID="node_3" TEXT="آناتومی و فیزیولوژی ریه">
      <node ID="node_19" TEXT="آناتومی سیستم تنفسی">
        <node ID="node_56" TEXT="راه هوایی فوقانی (بینی، فارنکس، لارنکس)">
        </node>
        <node ID="node_57" TEXT="راه هوایی تحتانی (تراشه، برونش‌ها، برونشیول‌ها)">
        </node>
        <node ID="node_58" TEXT="عضلات تنفسی (دیافراگم، بین دنده‌ای)">
        </node>
        <node ID="node_59" TEXT="پلور و فضای توراکس">
        </node>
      </node>
      <node ID="node_20" TEXT="نکات آناتومیک">
        <node ID="node_60" TEXT="نقش بینی: فیلتر، مرطوب و گرم کردن هوا">
        </node>
        <node ID="node_61" TEXT="آدنوئید/لوزه‌ها: ایجاد انسداد در مسیر هوایی">
        </node>
        <node ID="node_62" TEXT="اپي‌گلوت: جلوگیری از ورود غذا به لارنکس">
        </node>
        <node ID="node_63" TEXT="تراشه: C شکل، حمایت غضروفی (320 درجه)">
        </node>
        <node ID="node_64" TEXT="باریک‌ترین قسمت راه هوایی در کودکان زیر 3 سال: کریکوئید">
        </node>
        <node ID="node_65" TEXT="باریک‌ترین قسمت راه هوایی در کودکان بالای 3 سال: گلوت">
        </node>
        <node ID="node_66" TEXT="تکامل راه هوایی: زمان تولد شکل‌گیری کامل است، طول و کالیبر افزایش می‌یابد (تا پایان قد نهایی)">
        </node>
        <node ID="node_67" TEXT="آلوئول‌ها: رشد آلوئول‌های جدید تا 8 سالگی کامل می‌شود.">
        </node>
      </node>
      <node ID="node_21" TEXT="فیزیولوژی ریه">
        <node ID="node_68" TEXT="عملکرد اصلی: تبادل گاز O2 و CO2">
        </node>
        <node ID="node_69" TEXT="مکانیسم ورود هوا">
          <node ID="node_130" TEXT="فشار منفی اینتراتوراسیک &lt; فشار اتمسفر">
          </node>
          <node ID="node_131" TEXT="دم: فعال (دیافراگم، عضلات بین دنده‌ای خارجی)">
          </node>
          <node ID="node_132" TEXT="بازدم: نرمال پسیو (در فعالیت/بیماری اکتیو)">
          </node>
        </node>
        <node ID="node_70" TEXT="حجم‌ها و ظرفیت‌ها">
          <node ID="node_133" TEXT="Tidal Volume (TV)">
          </node>
          <node ID="node_134" TEXT="FRC (ظرفیت باقی مانده عملکردی)">
          </node>
          <node ID="node_135" TEXT="Total Lung Capacity (TLC)">
          </node>
          <node ID="node_136" TEXT="Residual Volume (RV)">
          </node>
          <node ID="node_137" TEXT="Vital Capacity (VC)">
          </node>
        </node>
        <node ID="node_71" TEXT="مقاومت راه‌های هوایی">
          <node ID="node_138" TEXT="تحت تاثیر: قطر و طول، ویسکوزیته، نوع جریان (لامینار/توربولانت)">
          </node>
          <node ID="node_139" TEXT="افزایش مقاومت: برونکواسپاسم، تنگی، جسم خارجی، تومور">
          </node>
          <node ID="node_140" TEXT="بیماری‌های Obstructive: آسم، CF">
          </node>
        </node>
        <node ID="node_72" TEXT="کمپلیانس ریه (تغییر حجم به ازای تغییر فشار)">
          <node ID="node_141" TEXT="کاهش کمپلیانس (Restrictive Lung Disease): فیبروز، ادم، افیوژن، ضعف عضلات، اسکولیوز">
          </node>
        </node>
        <node ID="node_73" TEXT="Gas Exchange">
          <node ID="node_142" TEXT="آلوئولار ونتیلیشن (تبادل گاز)">
          </node>
          <node ID="node_143" TEXT="فضای مرده آناتومیک (30% هوای تنفسی، ثابت)">
          </node>
        </node>
      </node>
    </node>
    <node ID="node_4" TEXT="علل هیپوکسی">
      <node ID="node_22" TEXT="Mismatch Ventilation/Perfusion (V/Q): آسم، BPD، آتلکتازی">
      </node>
      <node ID="node_23" TEXT="هیپوونتیلیشن: آپنه، Narcotic overdose، بیماری‌های نوروماسکولار">
      </node>
      <node ID="node_24" TEXT="Extra pulmonary Shunt: CHD (مشکلات قلبی)">
      </node>
    </node>
    <node ID="node_5" TEXT="سرفه (Cough)">
      <node ID="node_25" TEXT="مکانیسم حیاتی برای حفاظت راه هوایی">
      </node>
      <node ID="node_26" TEXT="مکانیسم سرفه">
        <node ID="node_74" TEXT="1. دم عمیق">
        </node>
        <node ID="node_75" TEXT="2. بسته شدن گلوت">
        </node>
        <node ID="node_76" TEXT="3. انقباض عضلات شکم و باز شدن سریع گلوت (بازدم با فشار)">
        </node>
      </node>
      <node ID="node_27" TEXT="عوامل موثر بر سرفه غیرمؤثر">
        <node ID="node_77" TEXT="مشکل در هر یک از مراحل سرفه (مثال SMA)">
        </node>
      </node>
      <node ID="node_28" TEXT="سرفه مداوم (Persistent)">
        <node ID="node_78" TEXT="علل: آسم، رینیت، سینوزیت، آلرژیک، برونشیت مزمن">
        </node>
        <node ID="node_79" TEXT="علل محیطی: دود سیگار، حیوان خانگی">
        </node>
      </node>
      <node ID="node_29" TEXT="نیاز به هیستوری دقیق از بیمار">
      </node>
    </node>
    <node ID="node_6" TEXT="شرح حال و معاینه کودک با بیماری تنفسی">
      <node ID="node_30" TEXT="نکات شرح حال">
        <node ID="node_80" TEXT="شروع و شکل مشکل تنفسی (حاد، مزمن، متناوب)">
        </node>
        <node ID="node_81" TEXT="فاکتورهای بهبود/بدتر شدن (مثال ورزش، شب)">
        </node>
        <node ID="node_82" TEXT="اکسپوژر محیطی (دود، حیوان)">
        </node>
        <node ID="node_83" TEXT="تغذیه (choking حین خوردن)">
        </node>
        <node ID="node_84" TEXT="Familial History (CF, atopy, نقص ایمنی, آسم)">
        </node>
      </node>
      <node ID="node_31" TEXT="انواع سرفه بر اساس زمان و شکل">
        <node ID="node_85" TEXT="سرفه صبحگاهی (رینیت، سینوزیت، عفونت برونشیال)">
        </node>
        <node ID="node_86" TEXT="سرفه شبانه (آسم، رفلاکس، PND)">
        </node>
        <node ID="node_87" TEXT="سرفه هنگام ورزش (آسم)">
        </node>
        <node ID="node_88" TEXT="سرفه عادتی/هیستریک (قطع هنگام حواس‌پرتی/خواب)">
        </node>
        <node ID="node_89" TEXT="سرفه حمله‌ای/پاروکسیسمال (سیاه سرفه)">
        </node>
        <node ID="node_90" TEXT="سرفه Croup (seal-like, خشن, brassy)">
        </node>
        <node ID="node_91" TEXT="شروع ناگهانی/Choking (آسپیریشن جسم خارجی)">
        </node>
      </node>
      <node ID="node_32" TEXT="معاینه فیزیکی">
        <node ID="node_92" TEXT="ارزیابی دیس پنه و دیسترس تنفسی">
        </node>
        <node ID="node_93" TEXT="Respiratory Rate (بر اساس سن متفاوت است)">
        </node>
        <node ID="node_94" TEXT="درجه تلاش تنفسی (افزایش کار تنفسی)">
        </node>
        <node ID="node_95" TEXT="علل افزایش کار تنفسی">
          <node ID="node_144" TEXT="در دم: Extrathoracic Obstruction (Croup, لارنگومالاشی، تنگی ساب گلوت)">
          </node>
          <node ID="node_145" TEXT="در دم: کاهش کمپلیانس ریه (پنومونی، ادم)">
          </node>
          <node ID="node_146" TEXT="در بازدم: Intrathoracic Obstruction (آسم، تراکئومالاشی)">
          </node>
        </node>
        <node ID="node_96" TEXT="علائم دیسترس تنفسی">
          <node ID="node_147" TEXT="Retractions (اینترکوستال، سوپرا استرنال)">
          </node>
          <node ID="node_148" TEXT="Nasal Flaring (پرش پره‌های بینی)">
          </node>
          <node ID="node_149" TEXT="استفاده از عضلات فرعی">
          </node>
        </node>
        <node ID="node_97" TEXT="صداهای تنفسی">
          <node ID="node_150" TEXT="Grunting (بازدم با فشار مقابل گلوت بسته)">
          </node>
          <node ID="node_151" TEXT="Stridor (صدای Harsh/Monophonic در دم، انسداد راه‌های هوایی بزرگ)">
          </node>
          <node ID="node_152" TEXT="Wheezing (صدای Partial Obstruction در بازدم، راه‌های هوایی کوچک)">
          </node>
          <node ID="node_153" TEXT="Rhonchi (صدای نامنظم ناشی از ترشحات در راه‌های هوایی اینتراتوراسیک)">
          </node>
          <node ID="node_154" TEXT="Crackles/Rales (صدای مایع/ترشحات در small airway)">
          </node>
          <node ID="node_155" TEXT="کاهش یا غیرقرینگی صدا (آتلکتازی، consolidation، افیوژن)">
          </node>
        </node>
      </node>
      <node ID="node_33" TEXT="الگوهای تنفسی">
        <node ID="node_98" TEXT="تاکی پنه: RR بالاتر از نرمال سن">
        </node>
        <node ID="node_99" TEXT="برادی پنه: کاهش RR">
        </node>
        <node ID="node_100" TEXT="هایپرپنه: افزایش عمق تنفسی">
        </node>
      </node>
      <node ID="node_34" TEXT="کلابینگ (Clubbing)">
        <node ID="node_101" TEXT="نشان‌دهنده مشکل اساسی ریوی، قلبی یا گوارشی">
        </node>
        <node ID="node_102" TEXT="شایع در CF و ILD">
        </node>
        <node ID="node_103" TEXT="هرگز در آسم دیده نمی‌شود">
        </node>
      </node>
    </node>
    <node ID="node_7" TEXT="روش‌های تشخیصی">
      <node ID="node_35" TEXT="تکنیک‌های تصویربرداری">
        <node ID="node_104" TEXT="CXR (روش اساسی): ارزیابی استخوان‌ها، قلب، عروق بزرگ، پارانشیم ریه">
        </node>
        <node ID="node_105" TEXT="Barium Esophagogram: ارزیابی دیسفاژی، رفلاکس، فیستول تراکئوازوفاژیال">
        </node>
        <node ID="node_106" TEXT="CT: انتخابی برای mass, ILD, برونشکتازی">
        </node>
        <node ID="node_107" TEXT="MRI: کاربرد محدود در پارانشیم، مفید برای ضایعات مدیاستن و عروق بزرگ">
        </node>
        <node ID="node_108" TEXT="Ultrasonography: مفید برای ارزیابی افیوژن، امپیما، mass، دیافراگم">
        </node>
      </node>
      <node ID="node_36" TEXT="پالس اکسی متری (Pulse Oximetry)">
        <node ID="node_109" TEXT="اندازه‌گیری O2 Saturation (اکسی هموگلوبین)">
        </node>
        <node ID="node_110" TEXT="روش راحت، غیرتهاجمی و قابل اعتماد (اگر پالس سالم باشد)">
        </node>
        <node ID="node_111" TEXT="عدم دقت">
          <node ID="node_156" TEXT="مشکل در هموگلوبین (مثال Carboxyhemoglobinemia)">
          </node>
          <node ID="node_157" TEXT="مت هموگلوبین">
          </node>
          <node ID="node_158" TEXT="پرفیوژن ضعیف (شوک، اندام سرد)">
          </node>
          <node ID="node_159" TEXT="لاک ناخن">
          </node>
        </node>
      </node>
      <node ID="node_37" TEXT="اندازه‌گیری غلظت CO2 (End-tidal CO2/Transcutaneous)">
      </node>
      <node ID="node_38" TEXT="تست عملکرد ریه (PFT)">
        <node ID="node_112" TEXT="اسپیرومتری: اندازه‌گیری حجم‌های ریوی">
        </node>
        <node ID="node_113" TEXT="Body Plethysmography: اندازه‌گیری RV, FRC, TLC">
        </node>
        <node ID="node_114" TEXT="PEFR (Peak Expiratory Flow Rate): کاربرد زیاد در آسم">
        </node>
        <node ID="node_115" TEXT="نازوفارنکوسکوپی (Flexible)">
        </node>
      </node>
    </node>
    <node ID="node_8" TEXT="اکسیژن‌رسانی و درمان دارویی">
      <node ID="node_39" TEXT="Oxygen Administration">
        <node ID="node_117" TEXT="هدف: SpO2 &gt; 95%">
        </node>
        <node ID="node_118" TEXT="روش‌ها: کانولای نازال، Simple Mask، Venture Mask، Reservoir Mask">
        </node>
        <node ID="node_119" TEXT="دستگاه‌های پیشرفته: HFNC, CPAP">
        </node>
        <node ID="node_116" TEXT="برونکوسکوپی (Rigid: choice برای Foreign Body; Flexible)">
        </node>
      </node>
      <node ID="node_40" TEXT="تراپی آئروسول">
        <node ID="node_120" TEXT="استفاده از برونکودیلاتورها، کورتیکواستروئیدها، آنتی‌بیوتیک‌ها">
        </node>
        <node ID="node_121" TEXT="روش‌ها: DPI (Dry Powder Inhaler), MDI (Method Dose Inhaler), Nebulizer">
        </node>
        <node ID="node_122" TEXT="نکته: DPI برای زیر 6 سال مناسب نیست.">
        </node>
      </node>
    </node>
    <node ID="node_9" TEXT="انسداد راه‌های هوایی">
      <node ID="node_41" TEXT="I. انسداد راه‌های هوایی فوقانی (Extrathoracic)">
        <node ID="node_123" TEXT="علل: فارنژیت، کروپ، لارنگومالاشی، جسم خارجی، آنژیوادم">
        </node>
        <node ID="node_124" TEXT="تشخیص: Stridor (معمولا در دم، در خواب کاهش می‌یابد)">
        </node>
        <node ID="node_125" TEXT="علائم همراه: Hoarseness, Aphonia (درگیری Vocal Cord)">
        </node>
      </node>
      <node ID="node_42" TEXT="II. بیماری‌های Lower Airway و پارانشیم">
        <node ID="node_126" TEXT="آسم (مهمترین) و پنومونی">
        </node>
        <node ID="node_127" TEXT="Viral-Induced Wheezing (در بچه‌های کوچک‌تر از 3 سال)">
        </node>
        <node ID="node_128" TEXT="Wheezing: صدای Continuous/Musical (بیشتر در بازدم)">
        </node>
        <node ID="node_129" TEXT="مکانیسم Wheezing: تنگی/کالپس راه‌های هوایی داخل توراکس در زمان بازدم (فشار داخل توراکس &gt; اتمسفر)">
        </node>
      </node>
    </node>
  </node>
</map>