<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
<!-- Generated by NotebookLM Corrected Mindmap Extractor v6.0 with X-Level Parent-Child Logic -->
  <node ID="node_0" TEXT="شوک در کودکان (اطفال)">
    <node ID="node_1" TEXT="تعریف و اصول کلی شوک">
      <node ID="node_7" TEXT="سیستم قلبی عروقی وظایف خود را از دست بدهد">
      </node>
      <node ID="node_8" TEXT="علل شوک در کودکان و بزرگسالان متفاوت است">
      </node>
      <node ID="node_9" TEXT="اختلال همودینامیک (فعالیت سیستم‌های جبرانی)">
      </node>
    </node>
    <node ID="node_2" TEXT="انواع شوک از نظر علت">
      <node ID="node_10" TEXT="Hypovolemic (هیپوولومی)">
        <node ID="node_36" TEXT="شایع‌ترین علت شوک در کودکان">
        </node>
        <node ID="node_37" TEXT="اختلال در جذب مایعات یا دفع زیاد">
        </node>
        <node ID="node_38" TEXT="مثال: گاستروانتریت">
        </node>
      </node>
      <node ID="node_11" TEXT="Cardiogenic (کاردیوژنیک)">
        <node ID="node_39" TEXT="انسداد در دریچه‌های قلبی">
        </node>
      </node>
      <node ID="node_12" TEXT="Distributive (توزیعی)">
        <node ID="node_40" TEXT="افزایش نفوذپذیری (permeability) جدار عروق">
        </node>
        <node ID="node_41" TEXT="خروج مایعات به فضای سوم">
        </node>
        <node ID="node_42" TEXT="مثال شایع: شوک سپتیک (سپسیس)">
        </node>
        <node ID="node_43" TEXT="مثال: شوک آنافیلاکسی">
        </node>
      </node>
      <node ID="node_13" TEXT="Obstructive (انسدادی)">
        <node ID="node_44" TEXT="حجم داخل عروق خوب است">
        </node>
        <node ID="node_45" TEXT="اجازه فانکشن در سیستم قلبی نیست">
        </node>
        <node ID="node_46" TEXT="مثال: تامپوناد، نوموتوراکس تنشن">
        </node>
      </node>
    </node>
    <node ID="node_3" TEXT="مراحل شوک">
      <node ID="node_14" TEXT="Compensated Shock (جبران شده)">
        <node ID="node_47" TEXT="مرحله اول و چند دقیقه‌ای">
        </node>
        <node ID="node_48" TEXT="سیستم‌های جبرانی فعال می‌شوند">
        </node>
        <node ID="node_49" TEXT="فشار خون ممکن است حفظ شود">
        </node>
      </node>
      <node ID="node_15" TEXT="Decompensated Shock (جبران نشده)">
        <node ID="node_50" TEXT="سیستم‌های جبرانی قدرت خود را از دست می‌دهند">
        </node>
        <node ID="node_51" TEXT="افت فشار خون (علامت اصلی)">
        </node>
        <node ID="node_52" TEXT="اختلال عملکرد ارگان‌ها">
        </node>
      </node>
      <node ID="node_16" TEXT="Irreversible Shock (غیرقابل برگشت)">
        <node ID="node_53" TEXT="علی‌رغم مداخلات قابل برگشت نیست">
        </node>
        <node ID="node_54" TEXT="Organ Damage">
        </node>
      </node>
    </node>
    <node ID="node_4" TEXT="علائم شوک (Clinical Criteria)">
      <node ID="node_17" TEXT="افت فشار خون (Decompensated)">
        <node ID="node_55" TEXT="نوزادان (۰-۲۸ روزه): زیر ۶۰">
        </node>
        <node ID="node_56" TEXT="شیرخواران (۱-۱۲ ماه): زیر ۷۰">
        </node>
        <node ID="node_57" TEXT="بچه ۱-۱۰ سال: کمتر از (۷۰ + سن × ۲)">
        </node>
        <node ID="node_58" TEXT="بعد از ۱۰ سال: کمتر از ۹۰">
        </node>
      </node>
      <node ID="node_18" TEXT="تب یا هیپوترمی">
      </node>
      <node ID="node_19" TEXT="تاکی‌کاردی (ضربان قلب بالا)">
      </node>
      <node ID="node_20" TEXT="تاکی‌پنه (تعداد تنفس بالا)">
      </node>
      <node ID="node_21" TEXT="انتهاها سرد (واکنش سیستم سمپاتیک)">
        <node ID="node_59" TEXT="سیانوز انتهاها">
        </node>
        <node ID="node_60" TEXT="Mottled skin (شبکه شبکه شدن پوست)">
        </node>
      </node>
      <node ID="node_22" TEXT="اختلال وضعیت هوشیاری (Mental Status)">
        <node ID="node_61" TEXT="استفاده از سیستم AVPU در کودکان">
        </node>
        <node ID="node_62" TEXT="A: Alert">
        </node>
        <node ID="node_63" TEXT="V: Verbal (پاسخ به صدا)">
        </node>
        <node ID="node_64" TEXT="P: Pain (پاسخ به درد)">
        </node>
        <node ID="node_65" TEXT="U: Unresponsive (عدم پاسخ)">
        </node>
      </node>
      <node ID="node_23" TEXT="کاهش حجم ادرار">
        <node ID="node_66" TEXT="کمتر از ۱ cc/kg/hr (غیرطبیعی)">
        </node>
        <node ID="node_67" TEXT="کمتر از ۰.۵ cc/kg/hr (معیار اصلی)">
        </node>
        <node ID="node_68" TEXT="آنوری (تولید نکردن ادرار)">
        </node>
      </node>
      <node ID="node_24" TEXT="CRT (Capillary Refilling Time)">
        <node ID="node_69" TEXT="بیشتر از ۲-۳ ثانیه نشان‌دهنده شدت شوک">
        </node>
      </node>
      <node ID="node_25" TEXT="ضعف نبض‌ها">
        <node ID="node_70" TEXT="نبض‌های محیطی (رادیال، پدال، آگزیلاری) ضعیف می‌شوند">
        </node>
        <node ID="node_71" TEXT="لمس نشدن نبض مرکزی (فمورال، کاروتید) نشانه دیسفانکشن قلبی-عروقی شدید">
        </node>
      </node>
    </node>
    <node ID="node_5" TEXT="Sepsis/Septic Shock">
      <node ID="node_26" TEXT="SIRS (Systemic Inflammatory Response Syndrome)">
        <node ID="node_72" TEXT="باید ۲ کرایتریا را داشته باشد">
        </node>
        <node ID="node_73" TEXT="دما: زیر ۳۶ یا بالای ۳۸.۵">
        </node>
        <node ID="node_74" TEXT="Respiratory Rate بالا">
        </node>
        <node ID="node_75" TEXT="WBC: خیلی بالا یا خیلی پایین (بر اساس سن)">
        </node>
      </node>
      <node ID="node_27" TEXT="مراحل شوک سپتیک">
        <node ID="node_76" TEXT="سپسیس (Sepsis): وجود SIRS + عفونت مستند یا مشکوک">
        </node>
        <node ID="node_77" TEXT="سپسیس شدید (Severe Sepsis): سپسیس + دیسفانکشن ۲ ارگان یا دیسفانکشن قلبی-عروقی/تنفس">
        </node>
        <node ID="node_78" TEXT="شوک سپتیک: سپسیس + اختلال کاردیاک و واسکولار">
        </node>
      </node>
    </node>
    <node ID="node_6" TEXT="درمان شوک (Resuscitation)">
      <node ID="node_28" TEXT="اقدام اولیه (Volume Resuscitation)">
        <node ID="node_79" TEXT="محلول ایزوتونیک (معمولاً نرمال سالین)">
        </node>
        <node ID="node_80" TEXT="دوز: ۲۰ cc/kg">
        </node>
        <node ID="node_81" TEXT="می‌تواند تا ۳-۴ بار تکرار شود">
        </node>
        <node ID="node_82" TEXT="لاکتات رینگر: توصیه نمی‌شود (تبدیل به کربنات، PCO2 بالا می‌رود)">
        </node>
      </node>
      <node ID="node_29" TEXT="Over Hydration (علائم)">
        <node ID="node_83" TEXT="شنیدن رال در سمع ریه (ادم ریه)">
        </node>
      </node>
      <node ID="node_30" TEXT="شروع آنتی‌بیوتیک و اصلاح الکترولیت‌ها">
        <node ID="node_84" TEXT="آنتی‌بیوتیک وریدی (IV) باید زود شروع شود">
        </node>
      </node>
      <node ID="node_31" TEXT="اقدام بعدی (اگر شوک برنگشت)">
        <node ID="node_85" TEXT="شروع اینوتروپ‌ها و وازوپرسورها">
          <node ID="node_94" TEXT="دوبوتامین (selective β1 agonist)">
          </node>
        </node>
      </node>
      <node ID="node_32" TEXT="استروئیدها (هیدروکورتیزون)">
        <node ID="node_86" TEXT="در صورت عدم پاسخ به تمام اقدامات">
        </node>
        <node ID="node_87" TEXT="برای نارسایی آدرنال ثانویه یا اولیه">
        </node>
      </node>
      <node ID="node_33" TEXT="تزریق خون (Packed Cell)">
        <node ID="node_88" TEXT="اگر هموگلوبین بیمار زیر ۱۰ باشد">
        </node>
      </node>
      <node ID="node_34" TEXT="اهداف درمانی (پایان فاز Resuscitation)">
        <node ID="node_89" TEXT="CRT زیر ۲ ثانیه">
        </node>
        <node ID="node_90" TEXT="انتهاها گرم">
        </node>
        <node ID="node_91" TEXT="Output ادرار &gt; ۱ cc/kg/hr">
        </node>
        <node ID="node_92" TEXT="فشار خون و وضعیت هوشیاری Stable شود">
        </node>
      </node>
      <node ID="node_35" TEXT="انتقال به PICU">
        <node ID="node_93" TEXT="بعد از رسیدن به اهداف درمانی">
        </node>
      </node>
    </node>
  </node>
</map>