<?xml version="1.0" encoding="UTF-8"?>
<map version="1.0.1">
<!-- Generated by NotebookLM Corrected Mindmap Extractor v6.0 with X-Level Parent-Child Logic -->
  <node ID="node_0" TEXT="مقدمات بیماری‌های کودکان و مراقبت عفونت‌های بیمارستانی">
    <node ID="node_1" TEXT="هدف پزشک (اصول)">
      <node ID="node_5" TEXT="شرح حال و معاینه فیزیکی">
        <node ID="node_21" TEXT="رسیدن به تشخیص مناسب">
        </node>
      </node>
      <node ID="node_6" TEXT="احتیاطات استاندارد (قبل از ورود به بیمارستان)">
        <node ID="node_22" TEXT="کمک به بیماران و درمان">
        </node>
      </node>
    </node>
    <node ID="node_2" TEXT="عفونت‌های همراه با مراقبت‌های بهداشتی (HAI)">
      <node ID="node_7" TEXT="تعریف (جلوگیری از انتقال)">
      </node>
      <node ID="node_8" TEXT="عفونت بیمارستانی (Nosocomial)">
        <node ID="node_23" TEXT="تعریف: 48 تا 72 ساعت بعد از مراجعه">
        </node>
        <node ID="node_24" TEXT="خطر بالا (سیستم دفاعی بیمار اشکال دارد)">
          <node ID="node_70" TEXT="گرم مثبت">
            <node ID="node_115" TEXT="استافیلوکوکوس اورئوس">
            </node>
            <node ID="node_116" TEXT="استافیلوکوکوس اپیدرمیدیس">
            </node>
          </node>
          <node ID="node_71" TEXT="گرم منفی (معضلات بزرگ)">
            <node ID="node_117" TEXT="سودوموناس آئوژینوزا">
            </node>
          </node>
          <node ID="node_72" TEXT="مایکوباکتریوم توبرکلوزیس (14 روز ایزوله)">
            <node ID="node_118" TEXT="مقاومت بالا به آنتی‌بیوتیک‌ها">
            </node>
          </node>
        </node>
      </node>
      <node ID="node_9" TEXT="علل ایجاد عفونت (میکروارگانیسم‌ها)">
        <node ID="node_25" TEXT="قارچ‌ها (مستعد کننده: آنتی‌بیوتیک وسیع‌الطیف)">
          <node ID="node_75" TEXT="کاندیدا (باعث Fungemia)">
          </node>
          <node ID="node_76" TEXT="آسپرژیلوس (انکولوژی و پیوند)">
          </node>
          <node ID="node_77" TEXT="اهمیت در بخش‌های ویژه (NICU، انکولوژی)">
          </node>
          <node ID="node_73" TEXT="Blood Born (HIV, HCV, HBV)">
          </node>
          <node ID="node_74" TEXT="غیر Blood Born (CMV, روبال, بروسلا)">
          </node>
        </node>
      </node>
      <node ID="node_10" TEXT="منبع عفونت بیمارستانی">
        <node ID="node_26" TEXT="اندوژن (فلور طبیعی فرد)">
          <node ID="node_78" TEXT="بیشتر باکتری‌ها">
          </node>
          <node ID="node_79" TEXT="عوامل خطر: کاتتر، آنتی بیوتیک وسیع، نقص ایمنی">
          </node>
        </node>
        <node ID="node_27" TEXT="اگزوژن (سایر افراد، سطوح، وسایل پزشکی)">
        </node>
      </node>
      <node ID="node_11" TEXT="انتقال عفونت">
        <node ID="node_28" TEXT="قطرات (Droplet)">
          <node ID="node_80" TEXT="شایع‌ترین راه (مثل کروناویروس‌ها)">
          </node>
          <node ID="node_81" TEXT="قطر بیشتر از 5 میکرون">
          </node>
          <node ID="node_82" TEXT="پاکسازی فضا: حدود 1 ساعت">
          </node>
        </node>
        <node ID="node_29" TEXT="هوا (Airborne)">
          <node ID="node_83" TEXT="قطر کمتر از 5 میکرون">
          </node>
          <node ID="node_84" TEXT="عفونت‌های شناسایی شده">
            <node ID="node_119" TEXT="آبله مرغان (Chicken Pox)">
            </node>
            <node ID="node_120" TEXT="سرخک (Measles) (بسیار مسری)">
            </node>
          </node>
          <node ID="node_85" TEXT="آنفولانزای پرندگان (احتیاطات N95)">
          </node>
        </node>
        <node ID="node_30" TEXT="تماس پوستی (Contact)">
          <node ID="node_86" TEXT="شستن صحیح دست‌ها (پیشگیری اصلی)">
          </node>
          <node ID="node_87" TEXT="استفاده از Hand Rub">
          </node>
        </node>
      </node>
      <node ID="node_12" TEXT="کنترل عفونت (شستشوی دست)">
        <node ID="node_31" TEXT="Hand Rub (الکل 70 درصد)">
          <node ID="node_88" TEXT="15 تا 30 ثانیه">
          </node>
          <node ID="node_89" TEXT="بین هر دو معاینه">
          </node>
          <node ID="node_90" TEXT="کارایی: 95 تا 96 درصد میکروارگانیسم‌ها">
          </node>
        </node>
        <node ID="node_32" TEXT="آب و صابون (لازم برای اسپورها/کلستریدیوم‌ها)">
        </node>
        <node ID="node_33" TEXT="مواد ضدعفونی تایید شده (WHO)">
          <node ID="node_91" TEXT="Chlorhexidine 2-4%">
          </node>
          <node ID="node_92" TEXT="Povidone Iodine 5-7.5%">
          </node>
          <node ID="node_93" TEXT="Triclosan 1%">
          </node>
          <node ID="node_94" TEXT="Alcoholic 70%">
          </node>
        </node>
      </node>
    </node>
    <node ID="node_3" TEXT="محافظت از خود (کادر درمان)">
      <node ID="node_13" TEXT="لزوم دریافت واکسن‌ها (پرسنل)">
        <node ID="node_34" TEXT="BCG">
        </node>
        <node ID="node_35" TEXT="HBV (هپاتیت B)">
        </node>
        <node ID="node_36" TEXT="کزاز (Tetanus)">
        </node>
        <node ID="node_37" TEXT="سرخجه (Rubella)">
        </node>
        <node ID="node_38" TEXT="آنفلوانزا (اندیکاسیون دارد)">
        </node>
        <node ID="node_39" TEXT="واریسلا (آبله مرغان)">
        </node>
      </node>
      <node ID="node_14" TEXT="نکات واکسیناسیون">
        <node ID="node_40" TEXT="MMR و BCG (دوز بعد از تولد) نیاز نیست">
        </node>
        <node ID="node_41" TEXT="تیتر HBsAb (سطح Protection) چک شود">
        </node>
        <node ID="node_42" TEXT="واکسن سه گانه (در صورت نیاز یادآور 10 سال بعد)">
        </node>
      </node>
      <node ID="node_15" TEXT="عفونت‌های خاص">
        <node ID="node_43" TEXT="HCV و HIV (واکسن ندارد)">
        </node>
        <node ID="node_44" TEXT="نیدل استیک (Needlestick)">
        </node>
      </node>
    </node>
    <node ID="node_4" TEXT="معاینه فیزیکی کودکان">
      <node ID="node_16" TEXT="مشکلات طب کودکان">
        <node ID="node_45" TEXT="شرح حال از والد/مراقب (برداشت دوم)">
        </node>
        <node ID="node_46" TEXT="عدم انتظار همکاری از کودک">
        </node>
        <node ID="node_47" TEXT="عدم وجود &apos;ترم مطلق&apos; (مبرم)">
        </node>
        <node ID="node_48" TEXT="علائم بالینی متفاوت با بزرگسالان">
        </node>
        <node ID="node_49" TEXT="تفاوت‌های فرهنگی (وحشت از دکتر)">
        </node>
        <node ID="node_50" TEXT="تداخل با وظایف پزشک (Googling)">
        </node>
      </node>
      <node ID="node_17" TEXT="گروه بندی سنی (بر اساس بیماری‌ها)">
        <node ID="node_51" TEXT="نوزاد (تا 28 روزگی، بیماری از مادر)">
        </node>
        <node ID="node_52" TEXT="شیرخوار (28 روزگی تا 1 سالگی)">
        </node>
        <node ID="node_53" TEXT="نوپا (1 تا 3 سالگی)">
        </node>
        <node ID="node_54" TEXT="مهدکودک/پیش‌دبستانی (3 تا 5 سالگی)">
        </node>
        <node ID="node_55" TEXT="دوران مدرسه (6 تا 12/18 سالگی)">
        </node>
        <node ID="node_56" TEXT="نوجوان (13 تا 19 سالگی)">
        </node>
      </node>
      <node ID="node_18" TEXT="نکات حائز اهمیت در شرح حال">
        <node ID="node_57" TEXT="Chief Complaint (علت مراجعه) (در سن پایین)">
        </node>
        <node ID="node_58" TEXT="تاریخچه تکاملی (Developmental history)">
        </node>
        <node ID="node_59" TEXT="تاریخچه واکسیناسیون (Immunization history)">
        </node>
        <node ID="node_60" TEXT="تاریخچه تغذیه‌ای (Nutritional history)">
        </node>
        <node ID="node_61" TEXT="تاریخچه اجتماعی (Social history)">
        </node>
        <node ID="node_62" TEXT="تاریخچه دوره نوزادی (Pediatric history)">
          <node ID="node_95" TEXT="سن حاملگی (Gestational Age)">
          </node>
          <node ID="node_96" TEXT="نمره آپگار (Apgar Score)">
          </node>
          <node ID="node_97" TEXT="آمنیوتیک مایع مکونیومی (Meconium Stained)">
          </node>
          <node ID="node_98" TEXT="خفگی (CP - Cerebral Palsy)">
          </node>
        </node>
      </node>
      <node ID="node_19" TEXT="اجزای معاینه فیزیکی">
        <node ID="node_63" TEXT="علائم حیاتی (Vital Signs)">
        </node>
        <node ID="node_64" TEXT="مشاهده (Inspection)">
        </node>
        <node ID="node_65" TEXT="لمس (Palpation) (اهمیت لنفادنوپاتی، ارگانومگالی)">
        </node>
        <node ID="node_66" TEXT="استفاده از وسایل (Instrumental Use)">
        </node>
      </node>
      <node ID="node_20" TEXT="معاینات اختصاصی">
        <node ID="node_67" TEXT="علائم حیاتی">
          <node ID="node_99" TEXT="فشار خون (معمولاً بالای 3 سال)">
          </node>
          <node ID="node_100" TEXT="دما (در همه موارد)">
          </node>
          <node ID="node_101" TEXT="قد، وزن، دور سر (حتماً در شیرخواران)">
          </node>
          <node ID="node_102" TEXT="مقایسه با صدک (Percentile)">
          </node>
          <node ID="node_103" TEXT="Turgor (تورگور پوست) (مهم در اسهال/کم‌آبی)">
          </node>
        </node>
        <node ID="node_68" TEXT="سر و صورت">
          <node ID="node_105" TEXT="ملاج (Fontanelle)">
            <node ID="node_121" TEXT="بیش از حد باز نباشد">
            </node>
            <node ID="node_122" TEXT="زود بسته نشده باشد">
            </node>
            <node ID="node_123" TEXT="دپرس یا Bulge نباشد">
            </node>
          </node>
          <node ID="node_106" TEXT="رفلکس قرمز (Red Reflex) (بررسی آب مروارید)">
          </node>
          <node ID="node_104" TEXT="چاقی و لاغری">
          </node>
        </node>
        <node ID="node_69" TEXT="قفسه سینه و تنفس">
          <node ID="node_107" TEXT="Rales و Wheezing (سمع)">
          </node>
          <node ID="node_108" TEXT="Rate (نرخ تنفسی)">
          </node>
          <node ID="node_109" TEXT="دیسترس تنفسی">
            <node ID="node_124" TEXT="استفاده از عضلات فرعی">
            </node>
            <node ID="node_125" TEXT="باز و بسته شدن پره‌های بینی">
            </node>
            <node ID="node_126" TEXT="اشکال در قلب، ریه، CNS، متابولیک">
            </node>
          </node>
          <node ID="node_110" TEXT="بررسی فتق نافی">
          </node>
          <node ID="node_111" TEXT="Organomegaly (بزرگی ارگان)">
          </node>
          <node ID="node_112" TEXT="Distension و انسداد">
          </node>
          <node ID="node_113" TEXT="معاینه لگن (تست‌های بارلو و اورتولانی)">
          </node>
          <node ID="node_114" TEXT="سیستم موسکولواسکلتال">
          </node>
        </node>
      </node>
    </node>
  </node>
</map>